version: "3.9"
services:
  web:
    build: . 
    container_name: app
    command: ["./.config/wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./env.db
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes: 
      - cache:/data      
  celery:
    build: .
    container_name: celery-app
    command: celery -A celery-app worker -l info --concurrency=1
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
  cache:
networks:
  appname:
    driver: bridge  
