name: docker-django-example #Project-Name

services:
  web:
    image: ${IMAGE_NAME}:${WEB_TAG}
    container_name: ${APP_NAME}-celery
    command: celery -A celery-app worker -l info --concurrency=1
    env_file:
      - ./.env
