name: docker-django-example #Project-Name
services:
  web:
    image: ${IMAGE_NAME}:${WEB_TAG}
    container_name: ${APP_NAME}-app
    command: uwsgi --ini uwsgi.ini
    env_file:
      - ./.env
  nginx:
        image: ${IMAGE_NAME}:${NGINX_TAG}
        container_name: ${APP_NAME}-nginx
        restart: always
        ports:
        - 80:80
        depends_on:
        - web