version: "3.9"
services:
  nginx:
    image: IMAGE_NAME:TAG
    container_name: app-name-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  web:
    image: IMAGE_NAME:TAG
    container_name: app-name
    command: uwsgi --ini uwsgi.ini
    ports:
      - 8000:8001
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.9-alpine3.16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./env.db
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes: 
      - cache:/data      
  celery:
    image: IMAGE_NAME:TAG
    container_name: celery-app
    command: celery -A celery-app worker -l info --concurrency=1
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
volumes:
  postgres_data:
  cache:
networks:
  appname:
    driver: bridge  
